### ISSUE TITLE
Subprojects list

### ISSUE THREAD

**Issue by dirksavage88** [ros-acceleration/community#23]
Hello,

I am trying to add a subproject for the stereo_image_proc accelerated disparity node but I do not see where to add in the subprojects.

should I make a pull request on the image_pipeline repo? The PR would be WIP, but need feedback from community on colcon build errors.

**Comment by vmayoral** [comment]
@dirksavage88, yeah, just sent a PR directly against https://github.com/ros-acceleration/image_pipeline. Happy to help debug issues together.

**Comment by vmayoral** [comment]
Closing this ticket @dirksavage88, feel free to open a new one if needed.
