### ISSUE TITLE
Taidacent HEX ZYNQ 7020 FPGA: add community support board

### ISSUE THREAD

**Issue by coleio** [ros-acceleration/community#26]
I would like to use this board to create low cost autonomous vehicles.  Need hw acceleration enabled to process visual odometry.

https://m.alibaba.com/product/1600074686709/lichee-tang-HEX-ZYNQ7020-FPGA-Development.html

**Comment by vmayoral** [comment]
That's a nice board @coleio. I encourage you to start checking [the instructions to add your board](https://github.com/ros-acceleration/community#adding-your-board) and start contributing.

Updated the issue title to reflect the board itself.

**Comment by coleio** [comment]
Every time I attempt to install vivado and vitis on my Ubuntu laptop it crashes the machine.  Can I use these tools on a cloud served vm?  I need vivado to create a petalinux image.

**Comment by vmayoral** [comment]
You should ask that in the Xilinx official forums and try to get there support to address your issues @coleio.

**Comment by vmayoral** [comment]
Closing in here due to inactivity. Re-open if you have any contributions in mind @coleio
