### ISSUE TITLE
Krs_beta and Krs 1.0 RC1: Which toolset to use?

### ISSUE THREAD

**Issue by pimartos** [ros-acceleration/community#29]
Hi, 
I would like to start porting acceleration_firmware_ultra96v2 for krs_beta/1.0. Looking at the [install instrucctions]( https://xilinx.github.io/KRS/sphinx/build/html/docs/install.html) it states that uses Ubuntu 20.04+vitis 2021.2+Ros2 Rolling
But Ros2 Rolling is a development distro, so it changes over time, so it would be better to use Humble (which has LTS up to May 2027). But, if I use Humble, it states that has binaries for Ubuntu 22.04 (which is also LTS up to April 2027), to use it on Ubuntu 20.04, I should install from sources
Besides that, Vitis is now on 2022.1, so which approach would be better? 
a)	Use Ubuntu 20.04+vitis 2021.2+Ros2 Humble? (similar to krs_alpha, only ROS2 change, but I need to build ROS2 from sources and there is no assurance about compatibility)
b)	Use Ubuntu 20.04+vitis 2021.2+Ros2 Rolling as stated in the install instructions? (But how can I assure that the Ros2 Rolling version used to built the firmware will be the same Ros2 Rolling version at later time?) 
c)	Use Ubuntu 22.04+vitis 2022.1+Ros2 Humble (which has LTS on ROS and Ubuntu and has the latest release of Vitis, but there is no assurance about compatibility and has a different toolset than krs_alpha)
Any thought/advice? 
Regards, 
Pedro

**Comment by vmayoral** [comment]
Hi @pimartos,

> I would like to start porting acceleration_firmware_ultra96v2 for krs_beta/1.0. Looking at the [install instrucctions](https://xilinx.github.io/KRS/sphinx/build/html/docs/install.html) it states that uses Ubuntu 20.04+vitis 2021.2+Ros2 Rolling

+1 to your effort. Regarding KRS (the Kria Robotics Stack), kindly refer to https://github.com/xilinx/KRS. Note KRS is owned by Xilinx (and I can't speak on their behalf anymore).

For what concerns the HAWG, happy to receive your port of course and to consider it for the [reference hardware platforms](https://github.com/ros-acceleration/community#reference-hardware-platforms). Pushing things to https://github.com/ros-acceleration/acceleration_firmware_ultra96v2 once you're ready will work best for community integration.

> But Ros2 Rolling is a development distro, so it changes over time, so it would be better to use Humble (which has LTS up to May 2027). But, if I use Humble, it states that has binaries for Ubuntu 22.04 (which is also LTS up to April 2027), to use it on Ubuntu 20.04, I should install from sources
> Besides that, Vitis is now on 2022.1, so which approach would be better?
> a) Use Ubuntu 20.04+vitis 2021.2+Ros2 Humble? (similar to krs_alpha, only ROS2 change, but I need to build ROS2 from sources and there is no assurance about compatibility)
> b) Use Ubuntu 20.04+vitis 2021.2+Ros2 Rolling as stated in the install instructions? (But how can I assure that the Ros2 Rolling version used to built the firmware will be the same Ros2 Rolling version at later time?)
> c) Use Ubuntu 22.04+vitis 2022.1+Ros2 Humble (which has LTS on ROS and Ubuntu and has the latest release of Vitis, but there is no assurance about compatibility and has a different toolset than krs_alpha)

I agree that now that Humble is out, we should stack to something more stable for the HAWG. On that regard, I'd encourage you to check the Humble Yocto recipes and add them to your project. See https://github.com/ros/meta-ros/pull/1003.

Accordingly, my advice would be to stick with `c)`.

**Comment by vmayoral** [comment]
Closing in here @pimartos but feel free to re-open or ping me if you still have more questions.
