### ISSUE TITLE
RobotPerf, a reference benchmarking suite that is used to evaluate robotics computing performance

### ISSUE THREAD

**Issue by vmayoral** [ros-acceleration/community#32]
*This ticket tracks the progress of the `RobotPerf` [subproject](https://github.com/ros-acceleration/community) of the ROS 2 Hardware Acceleration Working Group. Content will be updated as we progress. In time, a repository will branch out of this effort and to its [own organization](https://github.com/robotperf) containing additional resources. Expectation however should be for the initial discussion to remain in here for organizational purposes. You can send feedback about this and/or participate by contacting [here](mailto:victor@accelerationrobotics.com)*.

#### `RobotPerf` project
<ins>Goal</ins>: Design and develop a reference benchmarking suite that is used to evaluate robotics computing performance with ROS 2. 

`RobotPerf` also aims to become a consortium of robotics leaders from academia, research labs, and industry whose mission is to *build fair and useful robotics benchmarks* that are technology agnostic, vendor-neutral and provide unbiased evaluations of robotics computing performance for hardware, software, and services—all conducted under prescribed conditions.

#### Rationale and motivation
Benchmarking is the act of running a computer program with a known workload to assess the program's relative performance. In the context of ROS 2, performance information can help roboticists design more efficient robotic systems and select the right hardware for their robotic application. It can also help understand the trade-offs between different algorithms that implement the same capability, and help them choose the best approach for their use case. Performance data can also be used to compare different versions of ROS 2 and to identify regressions. Finally, performance information can be used to help prioritize future development efforts.

The myriad combinations of robot hardware and robotics software make assessing robotic-system performance in an architecture-neutral, representative, and reproducible manner challenging. `RobotPerf` attempts to provide a reference benchmarking suite that is used to evaluate robotics computing performance built with ROS 2.

#### Why ROS 2
Robot behaviors take the form of computational graphs, with data flowing between computation Nodes, across physical networks (communication buses) and while mapping to underlying sensors and actuators. The popular choice to build these computational graphs for robots these days is the Robot Operating System (ROS)[^3], a framework for robot application development. ROS enables you to build computational graphs and create robot behaviors by providing libraries, a communication infrastructure, drivers and tools to put it all together. Most companies building real robots today use ROS or similar event-driven software frameworks. ROS is thereby the common language in robotics, with several [hundreds of companies](https://github.com/vmayoral/ros-robotics-companies) and thousands of developers using it everyday. ROS 2 [^4] was redesigned from the ground up to address some of the challenges in ROS and solves many of the problems in building reliable robotics systems.

[^3]: Quigley, M., Conley, K., Gerkey, B., Faust, J., Foote, T., Leibs, J., ... & Ng, A. Y. (2009, May). ROS: an open-source Robot Operating System. In ICRA workshop on open source software (Vol. 3, No. 3.2, p. 5).
[^4]: Macenski, S., Foote, T., Gerkey, B., Lalancette, C., & Woodall, W. (2022). Robot Operating System 2: Design, architecture, and uses in the wild. Science Robotics, 7(66), eabm6074.

ROS 2 presents a modern and popular framework for robot application development most silicon vendor solutions support, and with a variety of modular packages, each implementing a different robotics feature that simplifies performance benchmarking in robotics.

#### Sponsorship
The project is open to sponsorships and collaborations. For sponsoring the `RobotPerf` project contact [here](mailto:victor@accelerationrobotics.com).

#### Milestones

(to be described)

**Comment by aording** [comment]
[Here](https://docs.google.com/presentation/d/1HStVPfiKSirbfqfYh8Ngc31KvUM07M5-oqe6pM-nA5s/edit#slide=id.g17da5d5c522_1_65) are the slides that were presented as part of this kick-off.

**Comment by jveejay** [comment]
[Here](https://docs.google.com/presentation/d/1HStVPfiKSirbfqfYh8Ngc31KvUM07M5-oqe6pM-nA5s/edit#slide=id.g17da5d5c522_1_65) are the slides we presented as part of this kick-off. 

Welcome suggestions, feedback and comments.

**Comment by vmayoral** [comment]
> [Here](https://docs.google.com/presentation/d/1HStVPfiKSirbfqfYh8Ngc31KvUM07M5-oqe6pM-nA5s/edit#slide=id.g17da5d5c522_1_65) are the slides we presented as part of this kick-off.

Thanks a lot for this, added them to the community repo at a29d9bfa2903367c36889f082a7f8474cbd5cced.
