### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AVJF1996** [ros-acceleration/community#33]
Hi, every body.

I want to choose an appropriate mini pc for my robotic application.
I want to know which part of my mini PC I should spend more money on.
The duty of the mini-pc is mainly to collect data from its I/O and emit the data over ROSnetwork, and maybe in the future, some ROS2 packages will be run on this mini-pc too.

As I know, most ROS packages run on the CPU and RAM, also Localhost, and for external communication nodes, send and receive from the network is mainly handled by the CPU and network card.

Should I spend more on my CPU and RAM, and network card?

Can ROS2 communicate effectively with 10Gb and 25Gb  card networks?

Are there any sources that guide me to the bottlenecks in components of computers for implementing ROS2?

Another question is how I should find that sending and proccing data on one local robotics core server and receiving from its server is faster than my computer processing data with my non-efficient algorithm. (due to the physical distance between my computer and the local robotics core server that couldn't be omitted)

Are there any sources to help me to find this type of question?

**Comment by vmayoral** [comment]
Most of these questions are very generic, and not specific about hardware acceleration. This community/group is for hardware acceleration matters. 

I'd suggest you bring them to the general [ROS Answers](https://answers.ros.org/questions/). Feel free to circle back in here if you have specific topics about hardware acceleration but our time's limited.
